apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: devsecops-updater
  namespace: argocd
spec:
  applicationRefs:
  - namePattern: devsecops-app
    useAnnotations: false
    images:
    - alias: devsecops-api
      imageName: 393818036545.dkr.ecr.us-east-1.amazonaws.com/devsecops-pipeline-secure
      commonUpdateSettings:
        updateStrategy: latest
        platforms:
        - linux/arm64
        pullSecret: ecr-credentials
    writeBackConfig:
      method: git
      gitConfig:
        branch: main
        writeBackTarget: "kustomization:apps/devsecops-app/overlays/production"
  commonUpdateSettings:
    allowedSourceTypes:
    - kustomize
    platforms:
    - linux/arm64
    pullSecret: ecr-credentials
