# gitops/manifests/flask-app/overlays/gke/patch-image.yaml
#
# Pipeline updates this file after every successful build.
# Image pulls from GCP Artifact Registry — no cross-cloud auth needed.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
spec:
  template:
    spec:
      containers:
        - name: api
          image: me-west1-docker.pkg.dev/project-31856ac9-76a2-472d-96c/devsecops-pipeline-secure/devsecops-api:sha-051aa663a7e96259d7cb52db0665e186cdb038a6