# gitops/manifests/flask-app/overlays/gke/patch-image.yaml
#
# Pipeline updates this file after every successful build.
# Image pulls from GCP Artifact Registry — no cross-cloud auth needed.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
spec:
  template:
    spec:
      containers:
        - name: api
          image: me-west1-docker.pkg.dev/project-31856ac9-76a2-472d-96c/devsecops-pipeline-secure/devsecops-api@sha256:7a6c35b9c3fc2b540a3ef5658c68dc52781702ae21d7ee7b2d4ba387bca4b8fa