# gitops/manifests/flask-app/overlays/gke/patch-image.yaml
#
# Pipeline updates this file after every successful build.
# Image pulls from GCP Artifact Registry — no cross-cloud auth needed.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
spec:
  template:
    spec:
      containers:
        - name: api
          image: me-west1-docker.pkg.dev/project-31856ac9-76a2-472d-96c/devsecops-pipeline-secure/devsecops-api@sha256:e8b489e46592ce10cb47c9e22dd827eee1314c35bce3c2351e365412e8ad256f