apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-pipeline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # The Image Updater looks at THESE annotations
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-api=393818036545.dkr.ecr.us-east-1.amazonaws.com/devsecops-pipeline-secure
    argocd-image-updater.argoproj.io/my-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/elorm116/devsecops-pipeline.git
    targetRevision: main
    path: k8s  # Pointing to the directory you just showed me
    directory:
      exclude: argocd-app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true