################################################################################
# servicemonitor.yaml — tells Prometheus to scrape /metrics on the Flask app
################################################################################
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devsecops-api
  namespace: monitoring          # must be in monitoring namespace
  labels:
    release: kube-prometheus     # must match Prometheus helm release label
spec:
  namespaceSelector:
    matchNames:
      - devsecops-app
  selector:
    matchLabels:
      app: devsecops-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s