apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    repo: https://kyverno.github.io/kyverno
    version: 1.17.1 # Match your installed version
    valuesFile: values.yaml