---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresher-sa
  namespace: devsecops-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresher-role
  namespace: devsecops-app
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresher-binding
  namespace: devsecops-app
subjects:
  - kind: ServiceAccount
    name: ecr-refresher-sa
    namespace: devsecops-app
roleRef:
  kind: Role
  name: ecr-refresher-role
  apiGroup: rbac.authorization.k8s.io