---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-ecr-creds
  namespace: devsecops-app
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA8o1If2xz9i1ANtHCOx20vQNiAVxw2GpxI1DWdNAsq98lPSyGF5VVLW6LeCWF/BJ53oGh4O7sTOnT2QegCzS93U+iNkc+PSpOa4pqGMAaAJSB5Eza2uxmTr1oej+o6IPb4xjXSGl5mxSC+oM4sR1vbTvFOGAz9AdCoit3hms69x+bbyCZLCZORfPxCu15cpv1NFBgLwpg0M8ychho2d1NJlAoOuw9oRs5UHNhvcLhlqB7bnRGDScv6NaFs/pzsWka7tM0nfvNLgrkHFmqTP05C+W/wOK6vOmKYcscDLjUQuqhpOARLa17GqxZmfOyx8NB0Bjs84e8moU0Tk7XdWuEvC5W3oYS4CRPzbJmmgLfsdJltdgtLQoD8FVXReT3Yog1Akemb3hrs/p3kjK7IbMFol4mwOxUhepE7vkSbj8peAJjKUkVW8guGX0BXi/Mlk8z/EBoZ36mpzs9vaMiIbIKULiQe2CaMzqxIGEK2sx7qC4WqD6Ff9OR/WzzWvf4FhU3u292mgBonOCyna4wEn0V7eCW4tbs8G8vt0a08eUABdrzyPnlK5QL90OY9qMJgzhJ/imv6TJ0+RxSF8Uz47z4ZCN1FeW+eZFPJcQUZ1CBq++ZEbI25YNi3Py2op0jZ8XOc5dmnhpM22zjqo3OgODoPFhY2Zx8evwaZCecsPibX8Bv0XFj0Fgvz23sMAN/d3K6lFo9JxzgG4lNm1/JexldmVFFyCA==
    AWS_SECRET_ACCESS_KEY: AgAM+EvQSZOYdo4ghcxtPBt6Csm1fFU5Glh9HzHbwQyfauwHRdPyE5a01YrpRl6GtnBb3xmvWU5uzCAyY4WO1kGz9uwsRZY+uFzV6uByef8IxtzLoJduJIwXb2an4N4MAEVEP+OlDGyNprEXZ08LS5inmw541vraaEy30pv5YnnDB0lImbibmKQqiKbqIwCqkNuwOTn+s+pCcuynCK4bhyF5iRwj3bMwlJX7V8YXVrPdKai/vZnNgOvGqUWm8t9IA7Kw5ux92v9NL5yY8U5VIf6dccW2EebLAyd4MkaIeOrBHnt8Qj7MImBJfA4ZjpYa8A3lfM+W2ArJyiOMj7YhbH7SbyPPZxg7B64F6KkPr/XkXcomln9wj/Z30SG0hHAQxdVgFVcoil6cYr2q+MGAKfur9Ou0q5XOqSWvIJ2xWKTysvJygYyZfIN/YJiXDcXGLlAXlJBH8sL5F3ZjC8Ds1/CR/VHjD0bJ4264TYSXo46pdAwM7e+I6GiuxnDaNn1M1vu9WgVSTd3FpOoOfAZi6+nMSjP0IB96VdEtSwxq9WdRqduwt+RYm/ACpnBgADef7646u2T3fYiGFmh1/TjLknKncJ8yopHGxeYseRNdCw7vZPVChLB27x563FxktbFtrMLgJPA8yj2CLGSmlDKUqE0zAtgynzEKaw8GeTubbX2AboL9pmRJa4HeUFjT2dZSNBLlO9hlLvU+9P5eHQdlWjRc42pUKQwcqdhrtFupTq3M9vqVzxSwujel
  template:
    metadata:
      name: aws-ecr-creds
      namespace: devsecops-app
