apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: devsecops-api
  managed-by: kustomize

images:
  - name: 393818036545.dkr.ecr.us-east-1.amazonaws.com/devsecops-pipeline-secure
    newName: 393818036545.dkr.ecr.us-east-1.amazonaws.com/devsecops-pipeline-secure
