#gitops/manifests/kyverno/policies/verify-image-signature.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
spec:
  webhookTimeoutSeconds: 30
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-signature
      match:
        any:
          - resources:
              namespaces:
                - devsecops-app
                - juice-shop
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
             # Matches both tag and digest references e.g. :sha-... and @sha256:...
            - "393818036545.dkr.ecr.us-east-1.amazonaws.com/devsecops-pipeline-secure*"
            - "393818036545.dkr.ecr.us-east-1.amazonaws.com/juice-shop*" #Juice-shop image registry, also signed with the same key
            - "me-west1-docker.pkg.dev/*/devsecops-pipeline-secure/*"
          imageRegistryCredentials:   # ✅ Correct for v1.17.1
            secrets:
              - name: regcred  # Note: In case you are following this guide, this secret must be created in the cluster and contain the necessary credentials to access the image registry, even if it's just for pulling public keys for signature verification.
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOI3OsCbTvpBB5jbMi7hQnwzkr2MT
                      fCJua07ps2P9UvLkJE20QPMkNoZ7tr5R8itACOTUE/bc0LVz3yIc1L6juw==
                      -----END PUBLIC KEY-----