apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elorm116/devsecops-pipeline.git
    targetRevision: main
    path: gitops/manifests/utils/sealed-secrets/overlays/pi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }