apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ingress.yaml # Points to your existing base ingress
  - backend-config.yaml

patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: add
        path: /metadata/annotations/cloud.google.com~1backend-config
        value: '{"default": "argocd-server-backend-config"}'