apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure

  routes:
    # Main Web UI
    - kind: Rule
      match: Host(`pi-argo.learndevops.site`)
      services:
        - name: argocd-server
          port: 80

    # gRPC support (very important for ArgoCD CLI)
    - kind: Rule
      match: Host(`pi-argo.learndevops.site`) && Headers(`Content-Type`, `application/grpc`)
      services:
        - name: argocd-server
          port: 80
          scheme: h2c