---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBdbNFHUUqOB5/M8LdnSOxEtjpKe7iiMFpaZRae+lw0MK+dNPz4gL8bgRAUZ/eH3MglogZR65HqVh9DCC5qDnpGOfAEq+XfqBJPGJMJF/2aam8/E2acQJ4Fvojy3/fOxpKsyZnYJQCcc9AAg9wRD7fHK29MSHLyNKNVsh52sSWq9hyl29O7ve03Rol2L+IPWMA1rltePgMSUwBZiJRynhuglyfVnQ2LDtOxj5oKyJegMC2Tw+qF0mVDAt63wnnMNFiIu+mVPc9Xx6ZLw4RzB9RcROQXbPKb+uymflGsW35Q80yyHtuje96FedGZABqwEahbRDGn2MwdfXw0LpcL+DdeQ4MuOprJg5QmHN3wKPZ1+O0FPH7AY+OJyS735raJF9B+Q+U61oXM4BL8VSk/glyf+B2mQw3Sis0/ynZa5/tW5TT0YPckmc/LPjxAQGHPnfgz0XxwTpyFfF/1jyLYohmsZ1XeIcTxvZajJfmDSbUnhpcymKWky7oKvq11fC/y8ZGHcaPXPbM4sCCMJNrO9j3veoJ/hqWGc5olUdOMGa4TY03S3FyKp3lhhproCeaTdRwxzd+lAVFUC7JjNLMmjjxkS/NKbqJVud1XLWbRmdx/XQ8cIMWcgu2bari9AYmrAc/87NDAdblybozfsXk8uMwBckoumTEyFFVZzd1IBDbpoo0OdklaCqoQ0MXHj/Fxwn1P9QhLRjCnHwtu7Q6r7SfYmWIne4HQ35z2SHr/EW9ARCgqj1k8QjwkaB+7Lg==
    admin-user: AgDHBnF4eCee9pnJH6weP4X7EuZSvK2bF8kGZ/ppwoRhJeluoKtGhlLWgNhMONsHoyecNP7ckfoHdlU+iobL1af+RZeX6ge+EWCNJbnkv85J9uhayHRndIrVrVMDet+dnp/BmcS6DrFEikf2727ENNyqcKmpYNqb8ko8tv7DlxR05XrhULvcauJGdPrwWxjy4t6TjJ686lK3yYq5nhiWGHEkJx+qInHonvC8Y08I9T3ZDFc2CnTFbz+rKTooVw2/ljzjUwMVwxZJ8jMCB5wwxgx7x3F4WmG4SYBjNPTHF5TWNU00WzbYsVY6QvI1Mk7k0ukWSCpo8GvuNiSpx8I6mPrYGt5MumAtn7uVnvryNlzP9XSsjViNbdyAY14PFckstQJAumouFwUh6gbleuGuN8f0SIr6PxetD8RbyyClLaCvNBDkzMDlT2GYjwLPtYpBiST5BF4trIRCIEJBKylWNEB+S6fKVcln72fB2EmcM8TjnMdspQeP+Z6ye6+48EBZnB+kI45JX+iplLfS+XF+xDiDrKIEJxcPOC9KwvkToqzOYZKgP/cebknBQUspwSoVSd5CoPhhmYhLt/g62YGs79u8b9Pe4dLqeswMttZVW6u1ZlGHnvQ5V/AceJiki+PguMxE/y5Kj1aS+7AO2THM97r2hcZsCWzLAScivEk02ttzQsZdB9Z+6uSd4rJZrVbpvhVMDnYtuA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
