apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: kube-system
data:
  config.yaml: |
    tunnel: cloudflared-tunnel
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: pi-argo.learndevops.site
        service: http://argocd-server.argocd:80
        originRequest:
          http2Origin: true
          noTLSVerify: true
      - service: http_status:404