    tunnel: cloudflared-tunnel
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: pi-argo.learndevops.site
        service: http://argocd-server.argocd:80
        originRequest:
          http2Origin: true
          noTLSVerify: true

      - hostname: web.learndevops.site
        service: http://devsecops-api.devsecops-app.svc.cluster.local:80
        originRequest:
          httpHostHeader: devsecops-api.devsecops-app.svc.cluster.local

      - service: http_status:404