---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgDTu14tu9D4HMCW9mVHOdLX7pu5gQHMKS0ErzalfHmF6RkJ8lyrNQ/LnVmOuHsH7jtcBj05Yld6hXPvOVZUfyhJUlx19ERrezg8amIneWq8ofgb8a+3yEr/dbJUnBu5GJWQFPjEc795+CdBnahf4Vn6iMa7RiL1uK9/pV7Q6C3P8YSBTSJC+eNzDKQ9hGAYUB/vadFbXHj6sUVntApbARuET5fEUX4YMw5zTEcwaICxKkPFOiDUw/qvu/Zt6b8Mz5nnXmeFyNWipcI1lGKdEqofGsyS2isFfTDWJcVK7wDnIp3hUMMMS+oMqLKpADcZ4wBH6AVS3FPGfeiOmkuuRjThiZqqPdMWpCNAvK64i1/F4mWoU4oqbZkemjSmz5OP6j7ChLz/6c7evZVjC2Lj+aLFPe5AtwbIcreAwVSiTLP2eHyYtm1h3C25U6eQ8VmMOgcU6O7asP2wLSw/JrqX4Ar5F5GpyNytUQ0XvDLIbVEy+ljVO9xf6QUMpUjq7Eg+ToLOMhExR2bX8aC58AXj6Uxg6LKaymf5XsGS8K1D7FpuPbKpYP2wous2/tHjdAwa4ZDOPOu2V13jnUvNiwgmYtIThnQFfiqLjJLIbcF1SoaIHVUM7E/9oa6VIMSKChYkushSHq0VPFHEJTePAUKbUQCMO/JKloUIsdxDGHuVg8jY3MXrbErH423Py3ujzbi/4JAzJD1jjqvbZ9oZfyg5YYZ6zTwjpcp0DWhRMoMXKmMxVAZQVz1Qlw0O7NW/fnnjKOLACb0/qfGHZw3RB2985zuu76poQ/Uc9w/fd+H6ke5kOkEnrSGx5KzoKzWFrVHBMiZDRIMtYuQi5mcDlFMVmYh/19sG1nRe/Ub+uJ3bCCeL+IM9LzIGbCrZOYkA/mlTc3QkEzhgidj7ww/ouoo2Ypb1q9Vb+lLg0sLl1tU0QVb0RLP/VqZKv1wDpg==
  template:
    metadata:
      name: cloudflared-token
      namespace: default
