---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflared-token
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAXtdiiYDQMdYMMVv8cQo/uJJZy5PBYhoL89to3cE6xzr3LqSi8CbBhkD+feg5qC5uL0pQGm9wDgOSfYDgLPlDnR1yeoFKUZwjSzBkOstE5Fwb5Av19G0usopICo/5WP5Cqg5BjtqeGjoChwjPi7anuTHZC1LIbz2ztrhm1ywHD9rxp7ERh7k6zQWP8YWQqblIxVkQ80UZFECL214v8XXTJgZYpGr61pK7MeONCLSl5vksz31uUTgt4eaZH+rCubYwSUBa+LJFYaHZUi1ZkYYALmhr0YB/o2U6I0KnZ3WJBMkx6nMYZ/d82ar5L3Fc1BTWy5v8sKWI2TwkzXDrJiAPvzf5i+KobC5Jzp4taiQuVZ1uq1p8BwWIMJtVIz+XpP75MTjUA9peVRWe6ibMV5xNB9+8nmgK2cxgKHtYmqvL7JthQDBFrODRNp9DcwKLuRZXJjsKhXvpEjMn07m62xl/iI1HF8V3bywePEaQvNQwM9S5GuFwuAKTcTtBLgb11bsgV2V5Ycr+JKfkEY6wLk4nnPFIvbutYMRiW3NYbjuAFaqnQ9CvHH0S+F3mTau/+AmPSTPl+5Z4zvRytxTnDJiuVeapVhmLnjd6TDynQfzUMImx6+iNENxgMhXJQFz39npyT13nJkk9gEUs+T+kYhiz3PmVzI3oOz3s4vxfDnxTZpYFAgtJEZOacHizDKMSXHDpItY3wM8j+PwspzKfiLi2knI+tPofRQRNMkbxGsStQfhFRFcBkaUSaKYWkTFe5a8B0cE34dBD7+KTI1WA1mvkbxs8zunYJNuiZPoWpygXf+SVss2ENf1Qb70Rchz/b+06ZJrjcoeZjQjLgeMXjye0rjgcSp5w+wGN+3obI+hbuGlfqsHYAWOblzYIlevtGtpPR0DC8pKSC/RA2iIUHYXu7H0GUHwAJNqlB4z8aEELkKnI4B9QVlOjL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflared-token
